name: Build Flatpak

on:
  push:
    branches: [ main ]
    tags:
      - "cursor-*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_ID: co.anysphere.cursor

jobs:
  post-renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    if: github.event_name == 'pull_request' && github.actor == 'renovate[bot]'
    outputs:
      changes_detected: ${{ steps.commit.outputs.changes_detected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      - name: Update checksums
        run: ./${APP_ID}/update-checksum.sh
      - name: Update metainfo
        run: ./${APP_ID}/update-metainfo.sh
      - name: Get last commit message
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: ${{ steps.last-commit.outputs.message }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          file_pattern: ${{ env.APP_ID }}/${{ env.APP_ID }}.yaml ${{ env.APP_ID }}/${{ env.APP_ID }}.metainfo.xml
      - name: Trigger build
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: ${{ github.workflow }}
          ref: ${{ github.head_ref }}

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: read
      checks: write
    needs: post-renovate
    if: >-
      always() && !cancelled() &&
      needs.post-renovate.result == 'skipped'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download previous repository (tags only)
        id: download-artifact
        if: github.ref_type == 'tag'
        uses: dawidd6/action-download-artifact@v3
        with:
          name: flatpak-repo
          path: repo
          branch: main
          workflow_conclusion: success
          if_no_artifact_found: ignore

      - name: Fix reppository directories
        if: steps.download-artifact.outcome == 'success'
        run: |
          mkdir -p repo/extensions repo/state repo/refs/mirrors repo/refs/remotes

      - name: Setup GPG
        env:
          GPG_KEY_GREP: ${{ secrets.GPG_KEY_GREP }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          gpg --list-keys --with-keygrip
          echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye
          echo "$GPG_PASSPHRASE" | /usr/libexec/gpg-preset-passphrase --preset "$GPG_KEY_GREP"
          echo "$GPG_PRIVATE_KEY" > repo.private.gpg
          gpg --import --batch repo.private.gpg
          rm repo.private.gpg

      - name: Clean branch name
        id: clean-branch-name
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          echo "branch=${BRANCH//\//-}" >> $GITHUB_OUTPUT

      - name: Build Flatpak
        id: build-flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ env.APP_ID }}.flatpak
          manifest-path: ${{ env.APP_ID }}/${{ env.APP_ID }}.yaml
          branch: ${{ steps.clean-branch-name.outputs.branch }}
          gpg-sign: ${{ secrets.GPG_KEY_ID }}

      - name: Update repo
        id: update-repo
        run: |
          flatpak build-update-repo \
            --gpg-sign="${{ secrets.GPG_KEY_ID }}" \
            --generate-static-deltas \
            --prune \
            repo

      - name: Initialize github-pages
        id: init-github-pages
        run: |
          cat <<EOF > repo/cursor.flatpakrepo
          [Flatpak Repo]
          Title=Cursor
          Url=https://kk-daniel.github.io/cursor-flatpak
          Homepage=https://cursor.com
          GPGKey=mQINBGgmv+ABEACi4nCDuHR/+AtTAfK6/4kS1pKlpQbSw5aS7E5+SLsFsBtC6th+eyi/kNQ6etcbA1IFuxjqg3opGtRgRcU35bmm7dWmUfvIdvZjo7oguM1DzuMKGZYcw1GxfuTfN8hrM3RvuoQLs0p3iS8GGMoJYXI1RM7zp/quG31qCppkjJmZpgkxDolfqAg8xvULTORX8msUrRTHr8C9xwmOJYFfbha1Z8HW9pMJsGdYBgUtixQkpWABVSQ34cXx/BG+89yp1asSZFkL3TKaw/vfa6CyggR1xD7YuTn0YHe11lKVv1r5q1iXksYf2spRdNnm4CQjbvo6T6PBByZcXZ07jjQUiaaWNakjJ6Kpd9aTCUx3GLqAYXiYcHZTDVn0fba6bdI44zgpp41SWl3NBGvPvvrvpnvr7yO2l/SlQ2ZfG0OfGbw+3r9Ad/OuEg044lPlbyDiYKPQ6VkrlCHJmgd7hxXU61NI/8xXDRO7qnUSOB0pRYKvTt5H39vKY/kMQPsCy5pbckc3C1Uvnmrbv1m74+wLYUDdsLhrRoBIG+VsewRqyK7yTBDzSBUNbi+ND3/deT9FnKubjTWy73AEASuUrxERKthGwkZLO3GsOsVo0f5dEPCWGfa4v6Xp7ky55zDVeDC1TuqRYWk7PRv2upUs9rhHwC0Yh0ez7nQzP8B76mEwwvqPOQARAQABtDpEYW5pZWwgTGluamFtYSAoa2stZGFuaWVsKSA8ZGFuaWVsLmxpbmphbWFAa2F0dG9rZXNrdXMuZmk+iQJXBBMBCgBBFiEEYV5y0Q+sCasu0Sn9yGKek+P7VMYFAmgmv+ACGwMFCQHhcjAFCwkIBwICIgIGFQoJCAsCBBYCAwECHgcCF4AACgkQyGKek+P7VMarcw//TYrZ+tikYL5I01Qa+Du4nmdj6cWc/vBRmwwdLaFLSbYN+U07uhka+npnpHDd0a/qseMf1hOu4Fxx3mYKgGwzp/mXwWJH6QkC7XU2AQF0NwL0BRXnpeCWGvSLX7atgwvOX8j/igBUEpEOx4JKYtghiXR+B/ON9o10YptoynSfIkE6GnsLZi127Hz9OgcOdMrCljTq8QcJjOSQb1Y72OVECfSGgohhC2rKTFkvQeO3eJJfqUkqtSq6vJT8qsvOJk8xBbK6pMXHErG1HEIOIk9Vn+Vm08yzDOOnz6Q68kDOWTyoewCFPz8JjRC1+SdtpLbR5ygp5BIbpVSDSP7KZFCwRsVwSN+3GF1CghJCMmvlCW/K/1POSUAVPkDZcT//dHaiKjh9mRr1zsXQ2EmIODrUS3CTJ53RZiinyvFJyOx/73myjSavEnIPgfzyEbhiSd2mEXMYlOef9o8ZQ9n1VBbJeKXLtRhtW5Ma6J+FV3rUPN6uBIOi1hl2Nd9iZ3FOaghoJHK8U7Md6nO3KocXjdgqVxxZJipzLPdQfvCHfKJbizNzdwY/fOHXBx9WKyYcWjrgpusJwVfyNuz/QYoej7SQ+WklfDpKV22e9PdEH7rt019q/3LLwuaL9rAIJDrvmzlG6Iw5lUXn4ny9sje1mhAfM1F49YBNimZvilStK6hmIoC5Ag0EaCa/4AEQALRdnvDL9khGqrFzbMX8NqPl4ijrueD73+8ZkpI9ysGIuhPN9+6shhu1c+6cGQYs+O9EBUJi4WdMkTgz1RRTBUcWSIQI0T3p9JG0j+dWVbC4RACBCHwb+JL7rg4auLI3cr0ZXh8O7z7xmPO/Yv7/xV9YE+XwP5gU023JzeG1L2uQi/euAjqEPktD6RVQoN221i8q2Y8Gluzg4XUqLgBcgr9YFWWyg/kmupdRxi2kGI5aZJYLRtn7hWvq5nScSeRbMPX5A9MOwM4Jg1E6EJiJL4Jk9Nuv3IzhrHRxnEnHbWGG7t4cGMfRXlNa9H2US6vMYywunVQuuFTOiyGYba0/f6EwF1i0Fn2aM+60mr+xJZuOWmtHIjf7zMMCfyg1kHWkLOLwz2IsNC+DEswUcHGrn82G+5n3uMVP586dMzfVAHZ/8G4tAPJISzJmAuzumF0t57wiAuuoak08AjLyRpjGtEla+BkuCiMce5tfwMlxHCewxej4EsSHkxLqUynL6tWVoaty43w6BnhG9bXFh56/kJdT+qosA7k4d6H9KyELhntFL8k8/9DNafpkyWPAnugum4nRz4sDDv2lK1bJWbWTzOXY3h2fy/zJ1OoqHhgOZur6dFae61awwChV8jryv1wGHHl4cOe4Hx97mbYNPORqDHqVKZU+gzssH8CjbOMpQcIzABEBAAGJAjwEGAEKACYWIQRhXnLRD6wJqy7RKf3IYp6T4/tUxgUCaCa/4AIbDAUJAeFyMAAKCRDIYp6T4/tUxiLnD/9kLgMugYd3Jirrr+hfJVv1zuWFpCbo0pgQB6klyV33JCivLPtFbk0JW4rx2pM4ZYUweWaC1ekT0B7rAOwdmAP9iXxV94+bC4jzURzg69dq5nFxApfQjOPHbgk4eDvVfQ4nfSYJ58Usbff1SqXXTfEg4VKX/fQbTo1HxUYg5Do7q47/l92h/n5ZHJNpp1gOfp7Uh3TGsmzfNic8noaYtcB0ojXJaRsBGdyA2DNDPTgaBWYSERrpwe7WnvsuvTmyIwxegdBUTmvFWoLIK7LbRWEvacMWNaJwF98/dvMPizPPhNJ6HWXN1HgagUVU2nfNDNL8cVga4N29FxGow9/bhfHYfvCPX8V32Y3OwMa12NYX7oMrE5wMQMWtoIRAV+8eBJb56RK+EuDWcGTgCfGxwVKjh+mKBzVfOA/goGOrQvFRuXLr7APXfVTuW/O4celBb1eMo0jmc6I66PymCh2a0bcMjaesFttGK5WaYwMYBcbmQY8JtS2jDQ7eDPFo5IgfZtWvp+Qp2qMm2VulFjPzlk7PC3dg3O+KDQr8mXUlpMo+KeLh/7IzeVYe/x7HkGX0O5eKwYfr0vWqvNSA3+SJBC2uEVbQ9esvtCJz7LHtlKR9/1zEvOlkHjmUNpI1aDNDodlImnTEegyzvISYXkLVuQc0ndGMcbN26YkOIbY3Xk7p+w==
          EOF

          cat <<EOF > repo/index.html
          <!DOCTYPE html>
          <html>
            <head>
              <title>Cursor Flatpak Repository</title>
            </head>
            <body>
              <h1>Cursor</h1>
              <p>This is a Flatpak repository for Cursor.</p>
              <p>To install Cursor, run the following commands:</p>
              <pre>
                flatpak remote-add --if-not-exists cursor-flatpak https://kk-daniel.github.io/cursor-flatpak/cursor.flatpakrepo
                flatpak install ${APP_ID}
              </pre>
            </body>
          </html>
          EOF

      - name: Upload repository as artifact (tags only)
        if: github.ref_type == 'tag'
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-repo
          path: repo/
          retention-days: 30

      - name: Save pages artifact
        id: save-repo
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo/

      - name: Publish check result
        uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ github.token }}
          name: Build Result
          conclusion: >-
            ${{ (steps.build-flatpak.conclusion == 'success' && steps.save-repo.conclusion == 'skipped' && 'failure' ) || (steps.build-flatpak.conclusion == 'success' && steps.save-repo.conclusion) || steps.build-flatpak.conclusion }}
          output: |
            {
              "summary": "${{ (steps.build-flatpak.conclusion == 'success' && steps.save-repo.conclusion == 'skipped' && 'failure' ) || (steps.build-flatpak.conclusion == 'success' && steps.save-repo.conclusion) || steps.build-flatpak.conclusion }}",
              "text_description":
                "Build flatpak: ${{ steps.build-flatpak.conclusion }}\nUpdate repo: ${{ steps.update-repo.conclusion }}\nInit github pages: ${{ steps.init-github-pages.conclusion }}\nSave repo: ${{ steps.save-repo.conclusion }}"
            }

  auto-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    if: >-
      always() && !cancelled() &&
      needs.build.result == 'success' &&
      github.ref == 'refs/heads/main' &&
      github.ref_type != 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Extract version
        id: extract-version
        if: github.ref == 'refs/heads/main' && github.ref_type != 'tag'
        run: |
          set -e

          # Extract version from the URL in the manifest
          SPEC="$(grep -A 3 'filename: appimage' ${APP_ID}/${APP_ID}.yaml)"
          URL="$(echo "$SPEC" | grep -o 'url: .*' | cut -d' ' -f2)"

          # Extract version from URL (e.g., Cursor-1.6.14-x86_64.AppImage -> 1.6.14)
          VERSION="$(echo "$URL" | sed -n 's/.*Cursor-\([0-9]\+\.[0-9]\+\.[0-9]\+\)-.*/\1/p')"

          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version from URL: $URL"
            exit 1
          fi

          echo "version=${VERSION}" >> $GITHUB_OUTPUT

          # Check if version was updated on this commit
          if git diff HEAD~1..HEAD ${APP_ID}/${APP_ID}.yaml | grep -A 3 'filename: appimage' | grep -q '^+\s*url: '
          then
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release
        if: steps.extract-version.outcome == 'success' && steps.extract-version.outputs.version-changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cursor-${{ steps.extract-version.outputs.version }}
          files: "*.flatpak"
          overwrite_files: true
          body: "Cursor ${{ steps.extract-version.outputs.version }}"
          prerelease: true

  deploy:
    if: >-
      always() && !cancelled() &&
      github.ref_type == 'tag' &&
      needs.build.result == 'success'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download flatpak artifact
        uses: actions/download-artifact@v4
        with:
          pattern: "*.flatpak"
      - name: Publish flatpak
        uses: softprops/action-gh-release@v2
        with:
          files: "*.flatpak"
          overwrite_files: true
          prerelease: false
      - name: Deploy github pages
        uses: actions/deploy-pages@v4
